# Set auto-connect minimum interval to 7.5ms
# CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6

# 11.25ms peripheral-to-central connection interval
# CONFIG_BT_PERIPHERAL_PREF_MAX_INT=9

# Latency=0 means peripheral won't skip any connection events, stays actively listening
# Helps prevent peripheral from sleeping too deeply to be woken by central, slightly increases power consumption
# CONFIG_BT_PERIPHERAL_PREF_LATENCY=0

# Connection timeout: if no communication for 4000ms, connection will be dropped
# CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=400

CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60

# Enable 32kHz crystal
CONFIG_CLOCK_CONTROL_NRF_K32SRC_XTAL=y
CONFIG_CLOCK_CONTROL_NRF_K32SRC_30PPM=y

# Enable rotary encoder
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# MOUSE
CONFIG_ZMK_POINTING=y

# CONFIG_ZMK_EXT_POWER=y

# Keyboard debounce settings
# CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5
# CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5
# CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# Enable keyboard RGB underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y
# CONFIG_LED_STRIP=y
# CONFIG_ZMK_RGB_UNDERGLOW_ON_START=y
# CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=3

# CONFIG_ZMK_SLEEP=y
# CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
# CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# This config file applies to both halves of the split keyboard
# Use left/right .conf files for half-specific settings

# Bluetooth enhancement
# CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=y
# CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# ZMK Studio (keymap editor)
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=n

